### ISSUE TITLE
You can marry yourself

### ISSUE THREAD

**Issue by Phanrazak** [velddev/Miki#4]
[](https://cdn.discordapp.com/attachments/160067691783127041/230595234675818497/unknown.png)

/shrug I'm not complaining

**Comment by Phanrazak** [comment]
https://cdn.discordapp.com/attachments/160067691783127041/230595234675818497/unknown.png

Idk if the picture is posted or not. Cause slow internet

**Comment by velddev** [comment]
This has been fixed, thank you 👍
